# Generated by Django 3.0.14 on 2021-12-12 10:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20211212_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='ticket',
            name='review_linked',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_linked', to='reviews.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='reviews.Ticket'),
        ),
    ]
